package yv.tils.migration

import data.Data
import yv.tils.migration.discord.DiscordMigrationLogic

/**
 * MigrationYVtils is a module for YVtils that handles the migration of data from previous versions.
 *
 * @deprecated This module will be removed with these releases:
 * yvtils-discord:4.1.0;
 * yvtils-smp:1.3.0;
 * yvtils-multiMine:1.3.0
 */
@Deprecated("This module will be removed with these releases: yvtils-discord:4.1.0; yvtils-smp:1.3.0; yvtils-multiMine:1.3.0")
class MigrationYVtils: Data.YVtilsModule {
    companion object {
        const val MODULE_NAME = "migration"
        const val MODULE_VERSION = "1.0.0"
    }

    override fun onLoad() {}

    override fun enablePlugin() {
        Data.addModule("$MODULE_NAME v$MODULE_VERSION")

        // Get which plugin is starting
        when (Data.pluginShortName) {
            "dc" -> {
                DiscordMigrationLogic().startMigration()
            }
        }
    }

    override fun onLateEnablePlugin() {

    }

    override fun disablePlugin() {

    }

    fun cleanUpMigrationTool() {
        // This function will be used to clean up any files generated by the migration tool
        // This will be called, when the migration logic is getting removed from the plugin
        // This will be called for one full minor version after the migration logic is removed
    }
}
