/*
 * Part of the YVtils Project.
 * Copyright (c) 2026 Lyvric / YVtils
 *
 * Licensed under the Mozilla Public License 2.0 (MPL-2.0)
 * with additional YVtils License Terms.
 * License information: https://yvtils.net/license
 *
 * Use of the YVtils name, logo, or brand assets is subject to
 * the YVtils Brand Protection Clause.
 */

package yv.tils.moderation.utils

import org.apache.logging.log4j.Level
import org.apache.logging.log4j.LogManager
import org.apache.logging.log4j.Marker
import org.apache.logging.log4j.core.Filter
import org.apache.logging.log4j.core.LogEvent
import org.apache.logging.log4j.core.Logger
import org.apache.logging.log4j.core.filter.AbstractFilter
import org.apache.logging.log4j.message.Message
import yv.tils.utils.logger.DEBUGLEVEL

/**
 * Log4j2 filter to suppress Mojang profile lookup warnings.
 *
 * This filter intercepts log messages that contain "Couldn't find profile with name"
 * which are generated by Mojang's authlib when a player profile lookup fails.
 * These are expected errors when a player name doesn't exist and don't need to be logged.
 *
 * The filter respects debug mode settings:
 * - When debug level is EXTRA (4) or higher, warnings will be shown
 * - Otherwise, warnings will be suppressed
 */
class MojangProfileLogFilter : AbstractFilter() {

    private fun shouldSuppressWarning(): Boolean {
        // Allow warnings to show when debug mode is EXTRA (4) or higher
        return !yv.tils.utils.logger.Logger.Companion::class.java.getDeclaredField("debugMode").apply {
            isAccessible = true
        }.getBoolean(null) ||
        yv.tils.utils.logger.Logger.Companion::class.java.getDeclaredField("debugLevel").apply {
            isAccessible = true
        }.getInt(null) < DEBUGLEVEL.EXTRA.level
    }

    override fun filter(event: LogEvent?): Filter.Result {
        if (event == null) return Filter.Result.NEUTRAL

        val message = event.message?.formattedMessage ?: return Filter.Result.NEUTRAL

        // Suppress Mojang profile lookup warnings (unless debug level is EXTRA or higher)
        if (event.level == Level.WARN &&
            message.contains("Couldn't find profile with name", ignoreCase = true) &&
            shouldSuppressWarning()) {
            return Filter.Result.DENY
        }

        return Filter.Result.NEUTRAL
    }

    override fun filter(
        logger: Logger?,
        level: Level?,
        marker: Marker?,
        msg: String?,
        vararg params: Any?
    ): Filter.Result {
        if (msg == null) return Filter.Result.NEUTRAL

        // Suppress Mojang profile lookup warnings (unless debug level is EXTRA or higher)
        if (level == Level.WARN &&
            msg.contains("Couldn't find profile with name", ignoreCase = true) &&
            shouldSuppressWarning()) {
            return Filter.Result.DENY
        }

        return Filter.Result.NEUTRAL
    }

    override fun filter(
        logger: Logger?,
        level: Level?,
        marker: Marker?,
        message: Any?,
        t: Throwable?
    ): Filter.Result {
        if (message == null) return Filter.Result.NEUTRAL

        val msg = message.toString()

        // Suppress Mojang profile lookup warnings (unless debug level is EXTRA or higher)
        if (level == Level.WARN &&
            msg.contains("Couldn't find profile with name", ignoreCase = true) &&
            shouldSuppressWarning()) {
            return Filter.Result.DENY
        }

        return Filter.Result.NEUTRAL
    }

    override fun filter(
        logger: Logger?,
        level: Level?,
        marker: Marker?,
        msg: Message?,
        t: Throwable?
    ): Filter.Result {
        if (msg == null) return Filter.Result.NEUTRAL

        val message = msg.formattedMessage

        // Suppress Mojang profile lookup warnings (unless debug level is EXTRA or higher)
        if (level == Level.WARN &&
            message.contains("Couldn't find profile with name", ignoreCase = true) &&
            shouldSuppressWarning()) {
            return Filter.Result.DENY
        }

        return Filter.Result.NEUTRAL
    }

    companion object {
        /**
         * Register this filter to the root logger to suppress Mojang profile lookup warnings globally.
         */
        fun register() {
            val rootLogger = LogManager.getRootLogger() as? Logger
            rootLogger?.addFilter(MojangProfileLogFilter())
        }
    }
}


